import Nav from "@/components/nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NAV_CONFIG } from "@/mockData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ts camp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav posts={NAV_CONFIG} />
        {children}
      </body>
    </html>
  );
}
